POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Fotógrafos",
    "description": "Fotógrafos que vão registrar os melhores momentos da sua festa.",
    "price": 3000,
    "image": "https://images.unsplash.com/photo-1552334823-ca7f70376914?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
  }

###

GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/692f7f435f13992bd5f11ee4

###
DELETE http://localhost:3000/api/services/692f7f435f13992bd5f11ee3

###
PUT http://localhost:3000/api/services/692f9dd3ad14f0a4e0ecb002
Content-Type: application/json

{
    "name": "Teste atualizado",
    "description": "Alguma descrição",
    "price": 3500,
    "image": "https://www.google.com/imgres?q=festa&imgurl=https%3A%2F%2Falphaconvites.com.br%2Fwp-content%2Fuploads%2F2023%2F01%2Ffesta-antes-formatura-scaled-1.jpg&imgrefurl=https%3A%2F%2Falphaconvites.com.br%2Ffestas-antes-da-formatura%2F&docid=c_egm3vO3ph3OM&tbnid=1HeNlkAwdZZtRM&vet=12ahUKEwiunvvuj6CRAxWKrZUCHRwMDfoQM3oECBIQAA..i&w=2560&h=1709&hcb=2&ved=2ahUKEwiunvvuj6CRAxWKrZUCHRwMDfoQM3oECBIQAA"
} 

###
POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Meu evento 2",
    "author": "Gustavo Oliveira",
    "description": "Meu primeiro evento de teste",
    "budget": 9000,
    "image": "https://www.google.com/imgres?q=festa&imgurl=https%3A%2F%2Falphaconvites.com.br%2Fwp-content%2Fuploads%2F2023%2F01%2Ffesta-antes-formatura-scaled-1.jpg&imgrefurl=https%3A%2F%2Falphaconvites.com.br%2Ffestas-antes-da-formatura%2F&docid=c_egm3vO3ph3OM&tbnid=1HeNlkAwdZZtRM&vet=12ahUKEwiunvvuj6CRAxWKrZUCHRwMDfoQM3oECBIQAA..i&w=2560&h=1709&hcb=2&ved=2ahUKEwiunvvuj6CRAxWKrZUCHRwMDfoQM3oECBIQAA",
    "services": [
        {
            "name": "Algum serviço 1 ",
            "description": "Alguma descrição",
            "price": 3000,
            "image": "https://www.google.com/imgres?q=festa&imgurl=https%3A%2F%2Falphaconvites.com.br%2Fwp-content%2Fuploads%2F2023%2F01%2Ffesta-antes-formatura-scaled-1.jpg&imgrefurl=https%3A%2F%2Falphaconvites.com.br%2Ffestas-antes-da-formatura%2F&docid=c_egm3vO3ph3OM&tbnid=1HeNlkAwdZZtRM&vet=12ahUKEwiunvvuj6CRAxWKrZUCHRwMDfoQM3oECBIQAA..i&w=2560&h=1709&hcb=2&ved=2ahUKEwiunvvuj6CRAxWKrZUCHRwMDfoQM3oECBIQAA"
        },
        {
            "name": "Algum serviço 2",
            "description": "Alguma descrição",
            "price": 1600,
            "image": "https://www.google.com/imgres?q=festa&imgurl=https%3A%2F%2Falphaconvites.com.br%2Fwp-content%2Fuploads%2F2023%2F01%2Ffesta-antes-formatura-scaled-1.jpg&imgrefurl=https%3A%2F%2Falphaconvites.com.br%2Ffestas-antes-da-formatura%2F&docid=c_egm3vO3ph3OM&tbnid=1HeNlkAwdZZtRM&vet=12ahUKEwiunvvuj6CRAxWKrZUCHRwMDfoQM3oECBIQAA..i&w=2560&h=1709&hcb=2&ved=2ahUKEwiunvvuj6CRAxWKrZUCHRwMDfoQM3oECBIQAA"
        }
    ]
}

###
GET http://localhost:3000/api/parties

###
GET http://localhost:3000/api/parties/692fab8d90a9563c0441f7eb

###
DELETE http://localhost:3000/api/parties/692fab8d90a9563c0441f7eC

###

PUT http://localhost:3000/api/parties/692faabe90a9563c0441f7e9
Content-Type: application/json

{
  "title": "Meu evento atualizado teste ",
  "author": "Gustavo Oliveira",
  "description": "Meu primeiro evento de teste",
  "budget": 9000,
  "image": "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "services": [
    
  ]
}


###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Gustavo user",
  "email": "gustavo@emailuserII.com",
  "password": "123456",
  "confirmPassword": "123456"
}


###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "gustavo@email.com",
  "password": "123456"
}

###
GET http://localhost:3000/api/admin/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OGZmNTNmMzg3NzY3NTE2ZGE2MTFhNCIsImlhdCI6MTc3MTA0MjExMSwiZXhwIjoxNzcxNjQ2OTExfQ.lcki_KfAoWrimO3GzBCtoVwIcjK8scYuoiuTu96mKpc

